<a href="https://colab.research.google.com/github/AlirezaSamari/Math/blob/main/Einsum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Einsum

In [ ]:
import torch

In [ ]:
x = torch.rand((2, 3))
x

tensor([[0.9698, 0.1287, 0.1541],
        [0.7328, 0.3059, 0.2810]])

***Premutation of Tensors***

In [ ]:
torch.einsum('ij->ji', x)

tensor([[0.9698, 0.7328],
        [0.1287, 0.3059],
        [0.1541, 0.2810]])

***Summation***

In [ ]:
torch.einsum('ij->', x)

tensor(2.5724)

***Column Sum***

In [ ]:
torch.einsum('ij->j', x)

tensor([1.7026, 0.4346, 0.4352])

***Column Sum***

In [ ]:
 torch.einsum('ij->i', x)

tensor([1.2526, 1.3198])

***Matrix-Vector Multiplication***

In [ ]:
v = torch.rand((1, 3))
torch.einsum('ij, kj-> ik', x, v)

tensor([[0.1763],
        [0.3313]])

***Matrix-Matrix Multipilication***

In [ ]:
y = torch.rand((3, 5))
torch.einsum('ij, jk->ik', x, y)

tensor([[0.5179, 0.1788, 0.2263, 0.3745, 0.7067],
        [0.4534, 0.3667, 0.3318, 0.5100, 0.6890]])

***DOT PRODUCT First Row with Second Row of Matrix***

In [ ]:
torch.einsum('i, i->', x[0], x[1])

tensor(0.7933)

***DOT PRODUCT First Row with Matrix***

In [ ]:
torch.einsum('ij, ij->', x, x)

tensor(1.6904)

***HADAMARD PRODUCT***

In [ ]:
torch.einsum('ij, ij-> ij', x, x)

tensor([[0.9405, 0.0166, 0.0238],
        [0.5370, 0.0936, 0.0790]])

***OUTER PRODUCT***
$${\color{green}C_{ij}} = {\color{red}a_i\color{blue}b_j}$$

In [ ]:
a = torch.arange(3)
b = torch.arange(3,7)
torch.einsum('i,j->ij', a, b)

tensor([[ 0,  0,  0,  0],
        [ 3,  4,  5,  6],
        [ 6,  8, 10, 12]])

***BATCH MATRIX MULTIPLICATION***
$${\color{green}C_{ijl}} = \sum_k{\color{red}A_{ijk}\color{blue}B_{ikl}} = {\color{red}A_{ijk}\color{blue}B_{ikl}}$$

In [ ]:
a = torch.rand(3,4,5)
b = torch.rand(3,5,6)
torch.einsum('ijk,ikl->ijl', a, b)

tensor([[[1.7842, 1.6131, 0.9676, 1.4573, 1.0928, 1.4636],
         [1.3199, 1.1868, 1.6237, 0.7255, 1.2334, 1.1498],
         [1.0988, 1.5848, 0.9574, 1.2396, 0.9055, 0.9374],
         [1.0955, 1.1937, 0.9788, 0.9828, 0.5068, 0.7681]],

        [[1.2336, 1.5610, 1.0057, 1.5755, 1.2138, 1.4702],
         [1.0029, 1.3512, 0.8867, 1.2471, 1.0922, 1.3939],
         [0.9721, 1.2514, 1.0199, 1.7002, 1.2429, 1.4656],
         [0.8458, 0.9953, 1.2746, 1.6844, 1.0164, 1.6640]],

        [[1.4916, 1.4618, 2.0479, 1.0815, 1.6750, 0.9637],
         [0.9451, 0.6885, 1.0444, 0.8117, 0.7696, 0.8238],
         [0.7415, 0.8467, 0.3939, 0.8218, 0.8198, 0.4971],
         [1.5844, 1.4524, 1.6291, 1.3825, 1.4019, 1.0677]]])

***Matrix Diagonal***

In [ ]:
x = torch.rand((3,3))
x

tensor([[0.7698, 0.7554, 0.5119],
        [0.6850, 0.0187, 0.6073],
        [0.5226, 0.1485, 0.4927]])

In [ ]:
torch.einsum('ii->i', x)

tensor([0.7698, 0.0187, 0.4927])

***Matrix Trace***

In [ ]:
torch.einsum('ii->', x)

tensor(1.2812)